# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test15testes():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_15testes(self):
    # Test name: 15testes
    # Step # | name | target | value | comment
    # 1 | open | / |  | 
    self.driver.get("https://atelielaudir.onrender.com/")
    # 2 | setWindowSize | 1436x769 |  | 
    self.driver.set_window_size(1436, 769)
    # 3 | click | css=.d-flex:nth-child(3) > .btn-primary |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".d-flex:nth-child(3) > .btn-primary").click()
    # 4 | type | id=loginEmail | test@gmail.com | 
    self.driver.find_element(By.ID, "loginEmail").send_keys("test@gmail.com")
    # 5 | type | id=loginPassword | 123 | 
    self.driver.find_element(By.ID, "loginPassword").send_keys("123")
    # 6 | click | css=.d-flex:nth-child(3) > .btn-primary |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".d-flex:nth-child(3) > .btn-primary").click()
    # 7 | click | id=tab-register |  | 
    self.driver.find_element(By.ID, "tab-register").click()
    # 8 | click | id=regEmail |  | 
    self.driver.find_element(By.ID, "regEmail").click()
    # 9 | click | css=.btn-outline-primary |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-outline-primary").click()
    # 10 | click | id=regEmail |  | 
    self.driver.find_element(By.ID, "regEmail").click()
    # 11 | type | id=regEmail | test@gmail.com | 
    self.driver.find_element(By.ID, "regEmail").send_keys("test@gmail.com")
    # 12 | type | id=regPassword | 1234567 | 
    self.driver.find_element(By.ID, "regPassword").send_keys("1234567")
    # 13 | click | css=.btn-outline-primary |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-outline-primary").click()
    # 14 | click | css=.d-flex:nth-child(3) > .btn-primary |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".d-flex:nth-child(3) > .btn-primary").click()
    # 15 | click | id=tab-login |  | 
    self.driver.find_element(By.ID, "tab-login").click()
    # 16 | click | css=.d-flex:nth-child(3) > .btn-primary |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".d-flex:nth-child(3) > .btn-primary").click()
    # 17 | click | id=loginPassword |  | 
    self.driver.find_element(By.ID, "loginPassword").click()
    # 18 | type | id=loginPassword | 123456 | 
    self.driver.find_element(By.ID, "loginPassword").send_keys("123456")
    # 19 | sendKeys | id=loginPassword | ${KEY_ENTER} | 
    self.driver.find_element(By.ID, "loginPassword").send_keys(Keys.ENTER)
    # 20 | click | css=.d-flex:nth-child(3) > .btn-primary |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".d-flex:nth-child(3) > .btn-primary").click()
    # 21 | click | id=tab-register |  | 
    self.driver.find_element(By.ID, "tab-register").click()
    # 22 | click | id=regEmail |  | 
    self.driver.find_element(By.ID, "regEmail").click()
    # 23 | click | id=regPassword |  | 
    self.driver.find_element(By.ID, "regPassword").click()
    # 24 | click | id=regPassword |  | 
    self.driver.find_element(By.ID, "regPassword").click()
    # 25 | type | id=regPassword | 123456 | 
    self.driver.find_element(By.ID, "regPassword").send_keys("123456")
    # 26 | click | css=.col-lg-5 .card-body |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".col-lg-5 .card-body").click()
    # 27 | click | css=.btn-outline-primary |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-outline-primary").click()
    # 28 | click | id=regEmail |  | 
    self.driver.find_element(By.ID, "regEmail").click()
    # 29 | type | id=regEmail | test1@gmail.com | 
    self.driver.find_element(By.ID, "regEmail").send_keys("test1@gmail.com")
    # 30 | click | css=.btn-outline-primary |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-outline-primary").click()
    # 31 | click | css=.btn-outline-primary |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-outline-primary").click()
    # 32 | click | id=regEmail |  | 
    self.driver.find_element(By.ID, "regEmail").click()
    # 33 | type | id=regEmail | test10@gmail.com | 
    self.driver.find_element(By.ID, "regEmail").send_keys("test10@gmail.com")
    # 34 | click | css=.btn-outline-primary |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-outline-primary").click()
    # 35 | click | id=loginEmail |  | 
    self.driver.find_element(By.ID, "loginEmail").click()
    # 36 | type | id=loginEmail | test10@gmail.com | 
    self.driver.find_element(By.ID, "loginEmail").send_keys("test10@gmail.com")
    # 37 | click | id=loginPassword |  | 
    self.driver.find_element(By.ID, "loginPassword").click()
    # 38 | click | id=loginPassword |  | 
    self.driver.find_element(By.ID, "loginPassword").click()
    # 39 | click | css=.d-flex:nth-child(3) > .btn-primary |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".d-flex:nth-child(3) > .btn-primary").click()
    # 40 | click | id=name |  | 
    self.driver.find_element(By.ID, "name").click()
    # 41 | type | id=name | itemnovo | 
    self.driver.find_element(By.ID, "name").send_keys("itemnovo")
    # 42 | click | id=description |  | 
    self.driver.find_element(By.ID, "description").click()
    # 43 | type | id=description | novoitem | 
    self.driver.find_element(By.ID, "description").send_keys("novoitem")
    # 44 | click | id=price |  | 
    self.driver.find_element(By.ID, "price").click()
    # 45 | type | id=price | 100 | 
    self.driver.find_element(By.ID, "price").send_keys("100")
    # 46 | click | css=.d-flex:nth-child(5) > .btn-primary |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".d-flex:nth-child(5) > .btn-primary").click()
    # 47 | mouseOver | id=btnClear |  | 
    element = self.driver.find_element(By.ID, "btnClear")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 48 | mouseOut | id=btnClear |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 49 | mouseDown | css=tr:nth-child(1) .btn-outline-primary |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) .btn-outline-primary")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 50 | mouseUp | css=tr:nth-child(2) .btn-outline-primary |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) .btn-outline-primary")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 51 | click | id=list |  | 
    self.driver.find_element(By.ID, "list").click()
    # 52 | click | css=tr:nth-child(1) .btn-outline-primary |  | 
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) .btn-outline-primary").click()
    # 53 | click | id=editName |  | 
    self.driver.find_element(By.ID, "editName").click()
    # 54 | type | id=editName | itemnovoa | 
    self.driver.find_element(By.ID, "editName").send_keys("itemnovoa")
    # 55 | click | id=editDescription |  | 
    self.driver.find_element(By.ID, "editDescription").click()
    # 56 | type | id=editDescription | novoitema | 
    self.driver.find_element(By.ID, "editDescription").send_keys("novoitema")
    # 57 | click | id=editPrice |  | 
    self.driver.find_element(By.ID, "editPrice").click()
    # 58 | click | id=saveEdit |  | 
    self.driver.find_element(By.ID, "saveEdit").click()
    # 59 | click | css=tr:nth-child(1) .btn-outline-primary |  | 
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) .btn-outline-primary").click()
    # 60 | click | id=saveEdit |  | 
    self.driver.find_element(By.ID, "saveEdit").click()
    # 62 | click | css=tr:nth-child(2) .btn-outline-danger |  | 
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) .btn-outline-danger").click()
    # 63 | assertConfirmation | Confirma exclusão do serviço? |  | 
    assert self.driver.switch_to.alert.text == "Confirma exclusão do serviço?"
    # 64 | webdriverChooseOkOnVisibleConfirmation |  |  | 
    self.driver.switch_to.alert.accept()
    # 65 | mouseOver | linkText=1 |  | 
    element = self.driver.find_element(By.LINK_TEXT, "1")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 66 | click | css=tr:nth-child(1) > td:nth-child(3) |  | 
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) > td:nth-child(3)").click()
    # 67 | click | id=inputSearch |  | 
    self.driver.find_element(By.ID, "inputSearch").click()
    # 68 | type | id=inputSearch | itemnovoaxx | 
    self.driver.find_element(By.ID, "inputSearch").send_keys("itemnovoaxx")
    # 69 | click | css=.col-lg-7 .card-title |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".col-lg-7 .card-title").click()
    # 70 | click | id=btnClearSearch |  | 
    self.driver.find_element(By.ID, "btnClearSearch").click()
    # 71 | click | id=name |  | 
    self.driver.find_element(By.ID, "name").click()
    # 72 | click | id=description |  | 
    self.driver.find_element(By.ID, "description").click()
    # 73 | type | id=description | test | 
    self.driver.find_element(By.ID, "description").send_keys("test")
    # 74 | click | id=price |  | 
    self.driver.find_element(By.ID, "price").click()
    # 75 | click | css=.d-flex:nth-child(5) > .btn-primary |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".d-flex:nth-child(5) > .btn-primary").click()
    # 76 | click | id=price |  | 
    self.driver.find_element(By.ID, "price").click()
    # 77 | click | id=name |  | 
    self.driver.find_element(By.ID, "name").click()
    # 78 | type | id=name | test | 
    self.driver.find_element(By.ID, "name").send_keys("test")
    # 79 | click | css=.d-flex:nth-child(5) > .btn-primary |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".d-flex:nth-child(5) > .btn-primary").click()
    # 80 | click | css=.d-flex:nth-child(5) > .btn-primary |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".d-flex:nth-child(5) > .btn-primary").click()
    # 81 | click | css=.d-flex:nth-child(5) > .btn-primary |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".d-flex:nth-child(5) > .btn-primary").click()
    # 82 | type | id=price | 10 | 
    self.driver.find_element(By.ID, "price").send_keys("10")
    # 83 | click | css=.d-flex:nth-child(5) > .btn-primary |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".d-flex:nth-child(5) > .btn-primary").click()
    # 84 | click | id=btnLogout |  | 
    self.driver.find_element(By.ID, "btnLogout").click()
    # 85 | mouseOver | css=tr:nth-child(2) .btn-outline-primary |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) .btn-outline-primary")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
  
